--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Prim69/PearlCooldownPro
build-by-default: true
branches:
- master
projects:
  PearlCooldownPro.PearlCooldownPro.PearlCooldownPro:
    path: ""
...
