#Cooldown in seconds
cooldown: 12

#Cooldown message, use {cooldown} for the time.
#Color - Use ยง for color as you normally would in Minecraft
message: "Please wait {cooldown} seconds before using an ender pearl."

